# ===========================================================================
# LOD 300 Structural Model — Test_Building
# Generated by SketchUp Auto Pipeline V3 (Vision LLM)
# Building: multi-storey | 2 floors | 7.0m total height
# Grid: 3x4 | Scale: 3.00 mm/px
# Member DB: 2 entries from schedule
# ===========================================================================

model  = Sketchup.active_model
model.name        = "Test_Building"
model.description = "multi-storey | 2 floors | Vision LLM V3"
ents   = model.active_entities
layers = model.layers
model.start_operation('LOD300 V3 Import', true)

# ── Layers ──
[
  "STR-Columns",
  "STR-Beams",
  "STR-Braces",
  "STR-Walls",
  "STR-Slabs",
  "STR-Foundations",
  "STR-Connections",
  "LOD300_UNMAPPED_NEEDS_REVIEW",
].each do |lname|
  layers[lname] || layers.add(lname)
end

# ── Materials ──
_mats = model.materials

_steel_mat = _mats["Structural_Steel"] || _mats.add("Structural_Steel")
_steel_mat.color = Sketchup::Color.new(160, 160, 175)

_concrete_mat = _mats["Concrete"] || _mats.add("Concrete")
_concrete_mat.color = Sketchup::Color.new(180, 175, 165)

_composite_mat = _mats["Composite"] || _mats.add("Composite")
_composite_mat.color = Sketchup::Color.new(200, 190, 140)

# ── Helper: get material by name ──
def _mat_for(material_name)
  case material_name.downcase
  when "steel" then _steel_mat
  when "concrete" then _concrete_mat
  when "composite" then _composite_mat
  else _steel_mat
  end
end

# ── Helper: IFC attributes ──
def _set_ifc(grp, mark, section, mtype)
  grp.set_attribute("IFC", "Mark",    mark)
  grp.set_attribute("IFC", "Section", section)
  grp.set_attribute("IFC", "Type",    mtype)
  grp.name = mark
end

# ========================================================================
# FLOOR: Base (Z: 0 → 3500 mm)
# ========================================================================

# ── Columns (4 members) ──

# ---- C_A1 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 0.0.mm, 0.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 0.0.mm, 3500.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_A1: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_A1", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_A1: #{e.message}"
end

# ---- C_A4 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 18000.0.mm, 0.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 18000.0.mm, 3500.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_A4: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_A4", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_A4: #{e.message}"
end

# ---- C_C1 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(12000.0.mm, 0.0.mm, 0.0.mm)
  _ep  = Geom::Point3d.new(12000.0.mm, 0.0.mm, 3500.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_C1: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_C1", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_C1: #{e.message}"
end

# ---- C_C4 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(12000.0.mm, 18000.0.mm, 0.0.mm)
  _ep  = Geom::Point3d.new(12000.0.mm, 18000.0.mm, 3500.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_C4: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_C4", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_C4: #{e.message}"
end

# ── Beams (3 members) ──

# ---- B_G1_0 | UB305x165x40 | beam | 6000mm | 80% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 0.0.mm, 0.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 6000.0.mm, 0.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP B_G1_0: zero-length"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-82.5, -151.7], [82.5, -151.7],
            [82.5, 151.7], [-82.5, 151.7]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Beams"] || layers.add("STR-Beams")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "B_G1_0", "UB305x165x40", "beam")
  end
rescue => e
  puts "SKIP B_G1_0: #{e.message}"
end

# ---- B_G1_1 | UB305x165x40 | beam | 6000mm | 80% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 6000.0.mm, 0.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 12000.0.mm, 0.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP B_G1_1: zero-length"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-82.5, -151.7], [82.5, -151.7],
            [82.5, 151.7], [-82.5, 151.7]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Beams"] || layers.add("STR-Beams")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "B_G1_1", "UB305x165x40", "beam")
  end
rescue => e
  puts "SKIP B_G1_1: #{e.message}"
end

# ---- B_G1_2 | UB305x165x40 | beam | 6000mm | 80% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 12000.0.mm, 0.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 18000.0.mm, 0.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP B_G1_2: zero-length"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-82.5, -151.7], [82.5, -151.7],
            [82.5, 151.7], [-82.5, 151.7]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Beams"] || layers.add("STR-Beams")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "B_G1_2", "UB305x165x40", "beam")
  end
rescue => e
  puts "SKIP B_G1_2: #{e.message}"
end


# ========================================================================
# FLOOR: FL1 (Z: 3500 → 7000 mm)
# ========================================================================

# ── Columns (4 members) ──

# ---- C_A1 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 0.0.mm, 3500.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 0.0.mm, 7000.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_A1: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_A1", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_A1: #{e.message}"
end

# ---- C_A4 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 18000.0.mm, 3500.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 18000.0.mm, 7000.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_A4: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_A4", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_A4: #{e.message}"
end

# ---- C_C1 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(12000.0.mm, 0.0.mm, 3500.0.mm)
  _ep  = Geom::Point3d.new(12000.0.mm, 0.0.mm, 7000.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_C1: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_C1", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_C1: #{e.message}"
end

# ---- C_C4 | UC203x203x46 | column | 85% ----
begin
  _sp  = Geom::Point3d.new(12000.0.mm, 18000.0.mm, 3500.0.mm)
  _ep  = Geom::Point3d.new(12000.0.mm, 18000.0.mm, 7000.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C_C4: zero-length (check coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-101.8, -101.6], [101.8, -101.6],
            [101.8, 101.6], [-101.8, 101.6]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Columns"] || layers.add("STR-Columns")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "C_C4", "UC203x203x46", "column")
  end
rescue => e
  puts "SKIP C_C4: #{e.message}"
end

# ── Beams (3 members) ──

# ---- B_G1_0 | UB305x165x40 | beam | 6000mm | 80% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 0.0.mm, 3500.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 6000.0.mm, 3500.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP B_G1_0: zero-length"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-82.5, -151.7], [82.5, -151.7],
            [82.5, 151.7], [-82.5, 151.7]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Beams"] || layers.add("STR-Beams")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "B_G1_0", "UB305x165x40", "beam")
  end
rescue => e
  puts "SKIP B_G1_0: #{e.message}"
end

# ---- B_G1_1 | UB305x165x40 | beam | 6000mm | 80% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 6000.0.mm, 3500.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 12000.0.mm, 3500.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP B_G1_1: zero-length"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-82.5, -151.7], [82.5, -151.7],
            [82.5, 151.7], [-82.5, 151.7]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Beams"] || layers.add("STR-Beams")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "B_G1_1", "UB305x165x40", "beam")
  end
rescue => e
  puts "SKIP B_G1_1: #{e.message}"
end

# ---- B_G1_2 | UB305x165x40 | beam | 6000mm | 80% ----
begin
  _sp  = Geom::Point3d.new(0.0.mm, 12000.0.mm, 3500.0.mm)
  _ep  = Geom::Point3d.new(0.0.mm, 18000.0.mm, 3500.0.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP B_G1_2: zero-length"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-82.5, -151.7], [82.5, -151.7],
            [82.5, 151.7], [-82.5, 151.7]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = layers["STR-Beams"] || layers.add("STR-Beams")
    _grp.material = _mat_for("Steel")
    _set_ifc(_grp, "B_G1_2", "UB305x165x40", "beam")
  end
rescue => e
  puts "SKIP B_G1_2: #{e.message}"
end


# ── Finalize ──
model.commit_operation
puts "LOD300 V3 Model import complete."

puts "  Floors: 2"
puts "  Columns: 8"
puts "  Beams: 6"
puts "  Walls: 0"
puts "  Total members: 14"