"""
Pipeline V2 — Zero-LLM Deterministic PDF → SketchUp Ruby Generator
============================================================================
Flow:
  PDF → PDFStructuredParser → GridMathEngine → Deterministic Ruby Coder → .rb

Produces true LOD300 structural model with:
  - Columns at every grid intersection × every level
  - Beams along every grid line × every level
  - Slabs covering each floor plate
  - Real-world coordinates from grid math (not LLM hallucination)
"""

import sys
import os
import json
import math
from pathlib import Path
from dataclasses import dataclass, field
from rich import print as rprint
from rich.console import Console
from rich.table import Table

sys.path.insert(0, '.')

from core.pdf_structured_parser import PDFStructuredParser, StructuredPageData, GridLabel
from agents.grid_math_engine import GridMathEngine, GridSystem, GridLine, LevelMarker

console = Console()

# =============================================================================
# LAYER & MATERIAL NAMES
# =============================================================================
LAYER_COLUMNS  = "STR-Columns"
LAYER_BEAMS    = "STR-Beams"
LAYER_SLABS    = "STR-Slabs"
LAYER_BRACES   = "STR-Braces"
LAYER_WALLS    = "STR-Walls"
LAYER_FOUND    = "STR-Foundations"
LAYER_UNMAPPED = "LOD300_UNMAPPED_NEEDS_REVIEW"

# =============================================================================
# RUBY TEMPLATES
# =============================================================================

RUBY_HEADER = '''# =============================================================================
# LOD 300 Structural Model — Auto-Generated by PDF-to-SketchUp Pipeline V2
# Model: Zero-LLM Deterministic  |  DO NOT EDIT — regenerate from pipeline_v2.py
# =============================================================================

model  = Sketchup.active_model
model.name        = "LOD300 Structural Model"
model.description = "Generated by PDF-to-SketchUp pipeline V2 (deterministic)"
ents   = model.active_entities
layers = model.layers
model.start_operation('LOD300 Structural Import', true)

def get_or_create_layer(layers, name)
  layers[name] || layers.add(name)
end

# ── Layers ────────────────────────────────────────────────────────────────────
["STR-Columns", "STR-Beams", "STR-Braces", "STR-Plates",
 "STR-Walls", "STR-Slabs", "STR-Foundations",
 "LOD300_UNMAPPED_NEEDS_REVIEW"].each do |lname|
  get_or_create_layer(layers, lname)
end

# ── Materials ─────────────────────────────────────────────────────────────────
_mats = model.materials
_steel_mat = _mats["Structural_Steel"] || _mats.add("Structural_Steel")
_steel_mat.color = Sketchup::Color.new(160, 160, 175)
_concrete_mat = _mats["Concrete"] || _mats.add("Concrete")
_concrete_mat.color = Sketchup::Color.new(180, 175, 165)

'''

# Standard column section: 400x400mm reinforced concrete
# (can be parameterized later)
DEFAULT_COLUMN_SIZE = 400  # mm — square RC column

# Standard beam section: 300x600mm RC beam
DEFAULT_BEAM_WIDTH  = 300  # mm
DEFAULT_BEAM_DEPTH  = 600  # mm

# Standard slab thickness: 150mm RC slab
DEFAULT_SLAB_THICKNESS = 150  # mm


def generate_column_ruby(mark: str, x_mm: float, y_mm: float, z_bottom: float,
                         z_top: float, width: int = DEFAULT_COLUMN_SIZE,
                         depth: int = DEFAULT_COLUMN_SIZE,
                         material: str = "concrete") -> str:
    """Generate Ruby code for a rectangular RC column at (x, y) from z_bottom to z_top."""
    half_w = width / 2.0
    half_d = depth / 2.0

    code = f'''# ---- {mark} | RC {width}x{depth} | column ----
begin
  _sp  = Geom::Point3d.new({x_mm:.1f}.mm, {y_mm:.1f}.mm, {z_bottom:.1f}.mm)
  _ep  = Geom::Point3d.new({x_mm:.1f}.mm, {y_mm:.1f}.mm, {z_top:.1f}.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP {mark}: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[{-half_w:.1f}, {-half_d:.1f}], [{half_w:.1f}, {-half_d:.1f}],
            [{half_w:.1f}, {half_d:.1f}], [{-half_w:.1f}, {half_d:.1f}]]
    _face = _ge.add_face(_raw.map {{ |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) }})
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "{LAYER_COLUMNS}")
    _grp.material = {'_concrete_mat' if material == 'concrete' else '_steel_mat'}
    _grp.set_attribute("IFC", "Mark",    "{mark}")
    _grp.set_attribute("IFC", "Section", "RC {width}x{depth}")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "{mark}"
  end
rescue => e
  puts "SKIP {mark}: #{{e.message}}"
end

'''
    return code


def generate_beam_ruby(mark: str, x1: float, y1: float, x2: float, y2: float,
                       z_level: float, width: int = DEFAULT_BEAM_WIDTH,
                       depth: int = DEFAULT_BEAM_DEPTH,
                       material: str = "concrete") -> str:
    """Generate Ruby code for a beam between (x1,y1) and (x2,y2) at z_level."""
    half_w = width / 2.0

    code = f'''# ---- {mark} | RC {width}x{depth} | beam ----
begin
  _sp  = Geom::Point3d.new({x1:.1f}.mm, {y1:.1f}.mm, {z_level:.1f}.mm)
  _ep  = Geom::Point3d.new({x2:.1f}.mm, {y2:.1f}.mm, {z_level:.1f}.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP {mark}: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[{-half_w:.1f}, 0], [{half_w:.1f}, 0],
            [{half_w:.1f}, {-depth:.1f}], [{-half_w:.1f}, {-depth:.1f}]]
    _face = _ge.add_face(_raw.map {{ |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) }})
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "{LAYER_BEAMS}")
    _grp.material = {'_concrete_mat' if material == 'concrete' else '_steel_mat'}
    _grp.set_attribute("IFC", "Mark",    "{mark}")
    _grp.set_attribute("IFC", "Section", "RC {width}x{depth}")
    _grp.set_attribute("IFC", "Type",    "beam")
    _grp.name = "{mark}"
  end
rescue => e
  puts "SKIP {mark}: #{{e.message}}"
end

'''
    return code


def generate_slab_ruby(mark: str, x_min: float, y_min: float, x_max: float, y_max: float,
                       z_level: float, thickness: int = DEFAULT_SLAB_THICKNESS,
                       material: str = "concrete") -> str:
    """Generate Ruby code for a slab covering the grid area at z_level."""
    code = f'''# ---- {mark} | RC {thickness}mm | slab ----
begin
  _grp = ents.add_group
  _ge  = _grp.entities
  _z  = {z_level:.1f}.mm
  _raw = [[{x_min:.1f}.mm, {y_min:.1f}.mm, _z],
          [{x_max:.1f}.mm, {y_min:.1f}.mm, _z],
          [{x_max:.1f}.mm, {y_max:.1f}.mm, _z],
          [{x_min:.1f}.mm, {y_max:.1f}.mm, _z]]
  _pts = _raw.map {{ |c| Geom::Point3d.new(*c) }}
  _face = _ge.add_face(_pts)
  _face.pushpull({-thickness}.mm) if _face
  _grp.layer = get_or_create_layer(layers, "{LAYER_SLABS}")
  _grp.material = {'_concrete_mat' if material == 'concrete' else '_steel_mat'}
  _grp.set_attribute("IFC", "Mark",    "{mark}")
  _grp.set_attribute("IFC", "Section", "RC {thickness}mm")
  _grp.set_attribute("IFC", "Type",    "slab")
  _grp.name = "{mark}"
rescue => e
  puts "SKIP {mark}: #{{e.message}}"
end

'''
    return code


def generate_ruby_footer() -> str:
    return '''
model.commit_operation
puts "LOD300 model loaded successfully."
puts "  Grid: #{model.active_entities.length} elements created."
'''


# =============================================================================
# MAIN PIPELINE
# =============================================================================

def run_pipeline_v2(pdf_path: str) -> dict:
    """
    Run the zero-LLM deterministic pipeline and generate Ruby script.
    """
    console.rule("[bold blue]PIPELINE V2 - Zero-LLM Deterministic PDF -> SketchUp[/]")

    # ── Step 1: Parse PDF ──────────────────────────────────────────────────
    console.print("[bold]Step 1:[/] Parsing PDF with PDFStructuredParser...")
    parser = PDFStructuredParser(pdf_path)
    pages = parser.parse_all()

    plan_pages      = [p for p in pages if p.page_type == 'plan']
    elevation_pages = [p for p in pages if p.page_type == 'elevation']
    other_pages     = [p for p in pages if p.page_type not in ('plan', 'elevation')]

    console.print(f"  Total pages: {len(pages)}")
    console.print(f"  Plan pages:  {len(plan_pages)}")
    console.print(f"  Elevation:   {len(elevation_pages)}")
    console.print(f"  Other:       {len(other_pages)}")

    # Show grid labels per plan page
    for p in plan_pages:
        labels = [(g.label, g.axis) for g in p.grid_labels]
        console.print(f"  Page {p.page_index}: grid = {labels}")

    # ── Step 2: Build Grid System ──────────────────────────────────────────
    console.print(f"\n[bold]Step 2:[/] Building Grid System via GridMathEngine...")
    engine = GridMathEngine(pages)
    grid_system = engine.build()

    console.print(f"  GridX ({len(grid_system.grids_x)}): {list(grid_system.grids_x.keys())}")
    console.print(f"  GridY ({len(grid_system.grids_y)}): {list(grid_system.grids_y.keys())}")
    console.print(f"  Levels ({len(grid_system.levels)}): {[(l.name, f'{l.z_mm:.0f}mm') for l in grid_system.levels]}")
    console.print(f"  Scale:  X={grid_system.scale_x:.3f}  Y={grid_system.scale_y:.3f}")
    console.print(f"  Confidence: {grid_system.confidence:.3f}")
    console.print(f"  BBox (mm): {grid_system.building_bbox_mm}")

    if grid_system.confidence < 0.2:
        rprint("[yellow]  WARNING: Low grid confidence. Model may be inaccurate.[/]")

    # ── Step 2b: Augment Levels ────────────────────────────────────────────
    # If engine found only 1 level but multiple plan pages exist,
    # force-generate levels: each plan page = one floor
    levels = list(grid_system.levels)
    if len(levels) <= 1 and len(plan_pages) >= 2:
        typical_floor_height_mm = 3500.0
        rprint(f"[yellow]  Only {len(levels)} level(s) found, but {len(plan_pages)} plan pages.[/]")
        rprint(f"[yellow]  Force-generating {len(plan_pages)} levels from plan pages.[/]")
        levels = []
        for i, page in enumerate(plan_pages):
            # Try extracting level name from page
            name = f"LEVEL_{i+1}"
            # Check page title in text tokens
            import re
            texts = sorted(page.all_text, key=lambda t: (t.cy, t.cx))
            for token in texts:
                t = token.text.strip().upper()
                m = re.search(r'(?:LEVEL|FLOOR|LVL|TẦNG|LẦU)\s*[-:.]?\s*(\d+)', t)
                if m:
                    name = f"LEVEL_{m.group(1)}"
                    break
            levels.append(LevelMarker(
                name=name,
                z_mm=i * typical_floor_height_mm,
                py=0,
                page=page.page_index,
                confidence=0.5,
            ))
        # Update grid_system for summary reporting
        grid_system.levels = levels
        rprint(f"  Augmented Levels: {[(l.name, f'{l.z_mm:.0f}mm') for l in levels]}")

    # ── Step 3: Generate Structural Elements ────────────────────────────────
    console.print(f"\n[bold]Step 3:[/] Generating structural elements (columns, beams, slabs)...")

    grids_x = grid_system.grids_x
    grids_y = grid_system.grids_y

    # Extract grid coordinates sorted by position
    x_labels = sorted(grids_x.keys(), key=lambda k: grids_x[k])
    y_labels = sorted(grids_y.keys(), key=lambda k: grids_y[k])
    x_coords = [grids_x[k] for k in x_labels]
    y_coords = [grids_y[k] for k in y_labels]

    # Sorted levels
    sorted_levels = sorted(levels, key=lambda l: l.z_mm)

    console.print(f"  Grid X positions (mm): {[f'{c:.0f}' for c in x_coords]}")
    console.print(f"  Grid Y positions (mm): {[f'{c:.0f}' for c in y_coords]}")
    console.print(f"  Level Z positions (mm): {[f'{l.z_mm:.0f} ({l.name})' for l in sorted_levels]}")

    ruby_code = RUBY_HEADER
    count_cols = 0
    count_beams = 0
    count_slabs = 0

    # ── 3a: Columns at every grid intersection ─────────────────────────────
    console.print(f"\n  [bold]3a: Columns[/] at all grid intersections...")

    # Build column levels list: each column spans from one level to the next,
    # or from level to level+floor_height if only one level exists
    column_levels = []
    if len(sorted_levels) >= 2:
        for li in range(len(sorted_levels) - 1):
            column_levels.append((sorted_levels[li].z_mm, sorted_levels[li+1].z_mm,
                                  sorted_levels[li].name, sorted_levels[li+1].name))
    else:
        # Single level → generate columns from z=0 to z=typical_floor_height
        typical_floor = 3500.0  # mm
        column_levels.append((0.0, typical_floor, "BASE", "LEVEL_1"))

    for i, xl in enumerate(x_labels):
        x_mm = x_coords[i]
        for j, yl in enumerate(y_labels):
            y_mm = y_coords[j]
            for z_bottom, z_top, lvl_name_b, lvl_name_t in column_levels:
                mark = f"COL_{xl}_{yl}_{lvl_name_b}"
                ruby_code += generate_column_ruby(
                    mark=mark, x_mm=x_mm, y_mm=y_mm,
                    z_bottom=z_bottom, z_top=z_top,
                    width=DEFAULT_COLUMN_SIZE, depth=DEFAULT_COLUMN_SIZE
                )
                count_cols += 1

    console.print(f"    Generated {count_cols} columns.")

    # ── 3b: Beams along grid lines ─────────────────────────────────────────
    console.print(f"\n  [bold]3b: Beams[/] along grid lines...")

    # X-direction beams (along Y grid lines, connecting X grid points)
    for li, level in enumerate(sorted_levels):
        z_top_of_floor = level.z_mm
        # Beams along each Y grid line
        for j, yl in enumerate(y_labels):
            y_mm = y_coords[j]
            for i in range(len(x_labels) - 1):
                x1 = x_coords[i]
                x2 = x_coords[i + 1]
                xl1 = x_labels[i]
                xl2 = x_labels[i + 1]

                mark = f"BM_X_{xl1}_{xl2}_{yl}_{level.name}"
                ruby_code += generate_beam_ruby(
                    mark=mark, x1=x1, y1=y_mm, x2=x2, y2=y_mm,
                    z_level=z_top_of_floor,
                    width=DEFAULT_BEAM_WIDTH, depth=DEFAULT_BEAM_DEPTH
                )
                count_beams += 1

    # Y-direction beams (along X grid lines, connecting Y grid points)
    for li, level in enumerate(sorted_levels):
        z_top_of_floor = level.z_mm
        for i, xl in enumerate(x_labels):
            x_mm = x_coords[i]
            for j in range(len(y_labels) - 1):
                y1 = y_coords[j]
                y2 = y_coords[j + 1]
                yl1 = y_labels[j]
                yl2 = y_labels[j + 1]

                mark = f"BM_Y_{xl}_{yl1}_{yl2}_{level.name}"
                ruby_code += generate_beam_ruby(
                    mark=mark, x1=x_mm, y1=y1, x2=x_mm, y2=y2,
                    z_level=z_top_of_floor,
                    width=DEFAULT_BEAM_WIDTH, depth=DEFAULT_BEAM_DEPTH
                )
                count_beams += 1

    console.print(f"    Generated {count_beams} beams.")

    # ── 3c: Slabs at each level ────────────────────────────────────────────
    console.print(f"\n  [bold]3c: Slabs[/] at each floor level...")

    if x_coords and y_coords:
        x_min, x_max = min(x_coords), max(x_coords)
        y_min, y_max = min(y_coords), max(y_coords)

        # Add some margin for slabs to overhang the grid
        margin = 500  # mm
        x_min -= margin
        y_min -= margin
        x_max += margin
        y_max += margin

        for li, level in enumerate(sorted_levels):
            # Slab on top of each level (except maybe the topmost roof level)
            z_slab = level.z_mm
            mark = f"SLAB_{level.name}"
            ruby_code += generate_slab_ruby(
                mark=mark,
                x_min=x_min, y_min=y_min,
                x_max=x_max, y_max=y_max,
                z_level=z_slab,
                thickness=DEFAULT_SLAB_THICKNESS
            )
            count_slabs += 1

    console.print(f"    Generated {count_slabs} slabs.")

    # ── Footer ─────────────────────────────────────────────────────────────
    ruby_code += generate_ruby_footer()

    # ── Step 4: Write Ruby Script ──────────────────────────────────────────
    console.print(f"\n[bold]Step 4:[/] Writing Ruby script...")
    output_dir = Path("output/final_ruby_scripts")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "lod300_model_v2.rb"

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(ruby_code)

    file_size_kb = output_path.stat().st_size / 1024
    console.print(f"  Output: {output_path}")
    console.print(f"  Size:   {file_size_kb:.1f} KB")

    # ── Summary ────────────────────────────────────────────────────────────
    console.rule("[bold green]PIPELINE V2 COMPLETE[/]")

    summary = Table(title="LOD300 Model Summary")
    summary.add_column("Element", style="cyan")
    summary.add_column("Count", style="green")
    summary.add_column("Details", style="white")
    summary.add_row("Columns", str(count_cols),
                    f"RC {DEFAULT_COLUMN_SIZE}x{DEFAULT_COLUMN_SIZE} at all grid intersections")
    summary.add_row("Beams", str(count_beams),
                    f"RC {DEFAULT_BEAM_WIDTH}x{DEFAULT_BEAM_DEPTH} along all grid lines")
    summary.add_row("Slabs", str(count_slabs),
                    f"RC {DEFAULT_SLAB_THICKNESS}mm at each level")
    summary.add_row("Total", str(count_cols + count_beams + count_slabs), "")
    summary.add_row("Grid", f"{len(x_labels)}×{len(y_labels)}",
                    f"X: {x_labels} | Y: {y_labels}")
    summary.add_row("Levels", str(len(sorted_levels)),
                    str([l.name for l in sorted_levels]))
    summary.add_row("Confidence", f"{grid_system.confidence:.1%}", "")
    console.print(summary)

    return {
        "ruby_path": str(output_path),
        "columns": count_cols,
        "beams": count_beams,
        "slabs": count_slabs,
        "total_elements": count_cols + count_beams + count_slabs,
        "grid_x_count": len(x_labels),
        "grid_y_count": len(y_labels),
        "level_count": len(sorted_levels),
        "confidence": grid_system.confidence,
        "error": None,
    }


# =============================================================================
# CLI Entry Point
# =============================================================================

if __name__ == "__main__":
    if len(sys.argv) < 2:
        rprint("[yellow]Usage:[/] python pipeline_v2.py <path_to_structural.pdf>")
        sys.exit(1)

    result = run_pipeline_v2(sys.argv[1])

    if result.get("error"):
        rprint(f"[red]FAILED:[/] {result['error']}")
        sys.exit(1)
    else:
        rprint(f"\n[bold green]SUCCESS![/] Ruby script: {result['ruby_path']}")
        rprint(f"  {result['total_elements']} elements generated "
               f"({result['columns']} cols + {result['beams']} beams + {result['slabs']} slabs)")